// declare module 'lodash'
// declare module 'classnames'
// declare module 'react'
declare module '*.less'
declare module 'react-dom'
declare module '@/*'
declare module '*.js'
declare module '../build/main/index'